name: Scan with Veracode

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      skip_tests: true
  veracode-scan:
    name: Perform scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Upload and scan
        uses: veracode/veracode-uploadandscan-action@master
        continue-on-error: true
        with:
          filepath: dist/cf-mendix-buildpack.zip
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          appname: ${{ secrets.VERACODE_APP_NAME }}
          sandboxid: ${{ secrets.VERACODE_SANDBOX_ID }}
          scantimeout: 15
          criticality: VeryLow
