name: Scan with Veracode

on:
  workflow_run:
    workflows: ["Deploy to Github Releases"]
    types:
      - completed

jobs:
  veracode-scan:
    name: Perform scan
    runs-on: ubuntu-latest
    steps:
      - name: Download PR artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deploy.yml
          branch: master
          name: dist
      - name: Upload and scan
        uses: veracode/veracode-uploadandscan-action@master
        with:
          filepath: 'cf-mendix-buildpack.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          appname: '${{ secrets.VERACODE_APP_NAME }}'
          sandboxid: '${{ secrets.VERACODE_SANDBOX_ID }}'
          scantimeout: 15
          criticality: 'VeryLow'
          