name: Push package for veracode scan

on: [push]
#  pull_request:
#    types: [closed]
#     branches:
#      - master

jobs:
#  pre:
 #   runs-on: ubuntu-latest
 #   outputs:
 #     skip: ${{ steps.skip-check.outputs.should_skip }}
 #   steps:
 #   - id: skip-check
 #     uses: fkirc/skip-duplicate-actions@master
 #     with:
 #       github_token: ${{ github.token }}
 #       paths_ignore: '["**.md", "dev/**"]'
  veracode-scan:
    name: veracode scan
    runs-on: ubuntu-latest
#    needs: pre
    steps:
      - name: Make java accessible
        uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
        with: 
          java-version: '8'
      - name: Copy artifact from repository
        uses: actions/upload-artifact@v2 # Copy files from repository to docker container so the next uploadandscan action can access them.
        with:
          path: cf-mendix-buildpack.zip # Wildcards can be used to filter the files copied into the container. See: https://github.com/actions/upload-artifact
      - name: Veracode scan
        uses: veracode/veracode-uploadandscan-action@master # Run the uploadandscan action. Inputs are described above.
        with:
          filepath: 'cf-mendix-buildpack.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          appname: ${{ secrets.VERACODE_APP_ID }}
          sandboxid: ${{ secrets.VERACODE_SANDBOX_ID }}
          scantimeout: 15
          criticality: 'VeryHigh'